#!/usr/bin/env python3
"""Merge capacity survey passes into docs/gpu-capacity.md, and catch the lie.

Upstream documents that OLLAMA_KV_CACHE_TYPE falls back to f16 WITHOUT TELLING
YOU on architectures that do not support a quantized cache. The variable is set,
the service restarts, models load and answer, and nothing changed. No error, no
log line - which is the exact failure mode this repo writes warnings about
everywhere else.

It comes with its own detector, though. If compression took effect, the same
model at the same context MUST use measurably less card memory than the f16
pass. If the number does not move, the setting did nothing, and this reports
FALLBACK rather than a number. That is why the report is a separate script from
the survey: the detection is only possible across passes.

    scripts/vram_report.py --out docs/gpu-capacity.md pass-f16.json pass-q8_0.json
    scripts/vram_report.py --self-check

Exit codes:
    0  report written
    1  a pass could not be read, or the f16 pass was missing
    2  bad arguments
"""

from __future__ import annotations

import argparse
import json
import sys

# Measurement noise on an otherwise idle card is tens of MiB. 100 MiB is
# comfortably above that and far below the GB-scale saving a working q8_0 pass
# produces, so it separates "did nothing" from "did something" without being
# sensitive to jitter.
FALLBACK_MARGIN_MIB = 100


def detect_fallback(f16_mib: int | None, quant_mib: int | None,
                    margin: int = FALLBACK_MARGIN_MIB) -> tuple[str, str]:
    """Did the quantized cache actually take effect? Three states, never two."""
    if f16_mib is None or quant_mib is None:
        return "UNKNOWN", "one of the two passes has no measurement to compare"
    saved = f16_mib - quant_mib
    if saved >= margin:
        return "APPLIED", f"{saved} MiB saved against f16"
    if saved <= -margin:
        return "UNKNOWN", (
            f"the quantized pass used {-saved} MiB MORE than f16, which is not a "
            "thing compression does - re-measure on an idle card")
    return "FALLBACK", (
        f"only {saved} MiB different from f16 - the setting silently did nothing "
        "on this architecture and the cache is still f16")


# Without this table the detector could be inverted and every report would
# cheerfully claim compression worked.
FALLBACK_CASES = (
    ("q8_0 halved the cache", 23465, 21000, "APPLIED"),
    ("saving exactly at the margin", 20100, 20000, "APPLIED"),
    ("saving one MiB short of the margin", 20099, 20000, "FALLBACK"),
    ("identical - the classic silent fallback", 20339, 20339, "FALLBACK"),
    ("noise in the wrong direction", 20339, 20350, "FALLBACK"),
    ("impossibly worse", 20000, 21000, "UNKNOWN"),
    ("no f16 measurement", None, 20000, "UNKNOWN"),
    ("no quantized measurement", 20000, None, "UNKNOWN"),
)


def self_check() -> list[str]:
    problems: list[str] = []
    for description, f16, quant, expected in FALLBACK_CASES:
        got, _ = detect_fallback(f16, quant)
        if got != expected:
            problems.append(
                f"detect_fallback {description!r}: got {got}, expected {expected} "
                "— the detector is broken, so a setting that silently did "
                "nothing would be reported as a working saving")
    return problems


def _key(row: dict) -> tuple:
    return (row["model"], row["num_ctx"])


def render(passes: list[dict]) -> str:
    base = next(p for p in passes if p["cache_type"] == "f16")
    base_rows = {_key(r): r for r in base["rows"]}
    others = [p for p in passes if p["cache_type"] != "f16"]

    lines = [
        "# GPU capacity, measured",
        "",
        "**Generated by `scripts/vram_report.py`. Do not hand-edit.**",
        "",
        "This file replaces the hand-maintained tables that used to live in",
        "`docs/gpu-host.md` and `docs/chat-models.md` and had already drifted",
        "apart from each other.",
        "",
        "A model's download size is not its VRAM footprint. Budget from the",
        "resident figure here, never from the tag.",
        "",
    ]
    for entry in passes:
        lines.append(
            f"- **{entry['cache_type']}** pass taken {entry['taken']}, idle "
            f"baseline {entry['baseline_mib']} MiB, flash attention "
            f"{'on' if entry['flash_attention'] else 'off'}")
    lines += [
        "",
        "The idle baseline matters: a survey taken while something else held the",
        "card is invalid on its face, which is how the first version of this",
        "table was produced.",
        "",
        "## Fit, by cache type",
        "",
        "| Model | Context | f16 | " + " | ".join(p["cache_type"] for p in others)
        + " |",
        "|---|---|---|" + "---|" * len(others),
    ]

    for key in sorted(base_rows):
        model, num_ctx = key
        row = base_rows[key]
        ctx = num_ctx if num_ctx is not None else "n/a"
        used = row["card_used_mib"]
        cells = [f"{row['verdict']} ({used} MiB)" if used else row["verdict"]]
        for entry in others:
            match = {_key(r): r for r in entry["rows"]}.get(key)
            if match is None:
                cells.append("not measured")
                continue
            state, _ = detect_fallback(used, match["card_used_mib"])
            cell = f"{match['verdict']}"
            if match["card_used_mib"]:
                cell += f" ({match['card_used_mib']} MiB)"
            if state == "FALLBACK":
                cell += " ⚠️ **FALLBACK**"
            cells.append(cell)
        lines.append(f"| `{model}` | {ctx} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "`FALLBACK` means the quantized cache setting silently did nothing on",
        "this architecture — the memory did not move. It is not an error state",
        "you can see any other way.",
        "",
        "## What this cannot tell you",
        "",
        "It measures whether a model **fits**. It says nothing about whether a",
        "compressed cache made the model **worse**. Memory is easy to measure and",
        "quality is not. Do not quote this file as evidence about output quality.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("passes", nargs="*", help="pass JSON files from vram_survey.py")
    parser.add_argument("--out", help="write the markdown report here")
    parser.add_argument("--self-check", action="store_true",
                        help="prove the fallback detector still works, then exit")
    args = parser.parse_args()

    if args.self_check:
        problems = self_check()
        for problem in problems:
            print(problem, file=sys.stderr)
        print("self-check: OK" if not problems else "self-check: FAILED")
        return 1 if problems else 0

    if not args.passes or not args.out:
        parser.print_usage(sys.stderr)
        print("give at least one pass file and --out", file=sys.stderr)
        return 2

    passes = []
    for path in args.passes:
        with open(path, encoding="utf-8") as handle:
            passes.append(json.load(handle))
    if not any(p["cache_type"] == "f16" for p in passes):
        print("no f16 pass given. Without the baseline nothing can be compared "
              "and the fallback detection cannot run", file=sys.stderr)
        return 1

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(render(passes))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
