#!/usr/bin/env python3
"""Merge capacity survey passes into docs/gpu-capacity.md, and catch the lie.

Upstream documents that OLLAMA_KV_CACHE_TYPE falls back to f16 WITHOUT TELLING
YOU on architectures that do not support a quantized cache. The variable is set,
the service restarts, models load and answer, and nothing changed. No error, no
log line - which is the exact failure mode this repo writes warnings about
everywhere else.

It comes with its own detector, though. If compression took effect, the same
model at the same context MUST use measurably less card memory than the f16
pass. If the number does not move, the setting did nothing, and this reports
FALLBACK rather than a number. That is why the report is a separate script from
the survey: the detection is only possible across passes.

    scripts/vram_report.py --out docs/gpu-capacity.md pass-f16.json pass-q8_0.json
    scripts/vram_report.py --self-check

(docs/gpu-capacity.md is not generated yet - that is a later task on this
branch. This script writes it; it does not exist until that task runs.)

Exit codes:
    0  report written
    1  a pass could not be read, or the f16 pass was missing
    2  bad arguments
"""

from __future__ import annotations

import argparse
import json
import sys

# Measurement noise on an otherwise idle card is tens of MiB. 100 MiB is
# comfortably above that and far below the GB-scale saving a working q8_0 pass
# produces, so it separates "did nothing" from "did something" without being
# sensitive to jitter.
FALLBACK_MARGIN_MIB = 100


def detect_fallback(f16_mib: int | None, quant_mib: int | None,
                    margin: int = FALLBACK_MARGIN_MIB) -> tuple[str, str]:
    """Did the quantized cache actually take effect? Three states, never two."""
    if f16_mib is None or quant_mib is None:
        return "UNKNOWN", "one of the two passes has no measurement to compare"
    saved = f16_mib - quant_mib
    if saved >= margin:
        return "APPLIED", f"{saved} MiB saved against f16"
    if saved <= -margin:
        return "UNKNOWN", (
            f"the quantized pass used {-saved} MiB MORE than f16, which is not a "
            "thing compression does - re-measure on an idle card")
    return "FALLBACK", (
        f"only {saved} MiB different from f16 - the setting silently did nothing "
        "on this architecture and the cache is still f16")


# Without this table the detector could be inverted and every report would
# cheerfully claim compression worked.
FALLBACK_CASES = (
    ("q8_0 halved the cache", 23465, 21000, "APPLIED"),
    ("saving exactly at the margin", 20100, 20000, "APPLIED"),
    ("saving one MiB short of the margin", 20099, 20000, "FALLBACK"),
    ("identical - the classic silent fallback", 20339, 20339, "FALLBACK"),
    ("noise in the wrong direction", 20339, 20350, "FALLBACK"),
    ("impossibly worse", 20000, 21000, "UNKNOWN"),
    ("exactly at the negative margin", 19900, 20000, "UNKNOWN"),
    ("one MiB short of the negative margin", 19901, 20000, "FALLBACK"),
    ("no f16 measurement", None, 20000, "UNKNOWN"),
    ("no quantized measurement", 20000, None, "UNKNOWN"),
)


def _key(row: dict) -> tuple:
    return (row["model"], row["num_ctx"])


def _adjusted(card_used_mib: int | None, baseline_mib: int) -> int | None:
    """nvidia-smi delta against this pass's own idle baseline - the measurement
    of record for FALLBACK detection. card_used_mib is whole-card and includes
    the baseline, so two passes taken minutes apart with different baselines
    are not comparable until this is subtracted from each independently."""
    if card_used_mib is None:
        return None
    return card_used_mib - baseline_mib


def render(passes: list[dict]) -> str:
    base = next(p for p in passes if p["cache_type"] == "f16")
    base_rows = {_key(r): r for r in base["rows"]}
    base_baseline = base["baseline_mib"]
    others = [p for p in passes if p["cache_type"] != "f16"]

    lines = [
        "# GPU capacity, measured",
        "",
        "**Generated by `scripts/vram_report.py`. Do not hand-edit.**",
        "",
        "This file replaces the hand-maintained tables that used to live in",
        "`docs/gpu-host.md` and `docs/chat-models.md` and had already drifted",
        "apart from each other.",
        "",
        "A model's download size is not its VRAM footprint. Budget from the",
        "resident figure here, never from the tag.",
        "",
    ]
    for entry in passes:
        lines.append(
            f"- **{entry['cache_type']}** pass taken {entry['taken']}, idle "
            f"baseline {entry['baseline_mib']} MiB, flash attention "
            f"{'on' if entry['flash_attention'] else 'off'}")
    lines += [
        "",
        "The idle baseline matters: a survey taken while something else held the",
        "card is invalid on its face, which is how the first version of this",
        "table was produced.",
        "",
        "The `FALLBACK` comparison below is baseline-adjusted — each pass's own",
        "idle baseline is subtracted before the two passes are compared — but the",
        "MiB figure shown in each cell is the absolute `nvidia-smi` reading, same",
        "as what an operator sees on the card. Do not treat the two as the same",
        "number.",
        "",
        "## Fit, by cache type",
        "",
        "| Model | Context | f16 " + ("| " + " | ".join(p["cache_type"] for p in others) + " |" if others else "|"),
        "|---|---|---|" + "---|" * len(others),
    ]

    other_rows = [{_key(r): r for r in entry["rows"]} for entry in others]
    all_keys = set(base_rows)
    for rows in other_rows:
        all_keys |= set(rows)

    for key in sorted(all_keys, key=lambda k: (k[0], k[1] if k[1] is not None else -1)):
        model, num_ctx = key
        row = base_rows.get(key)
        ctx = num_ctx if num_ctx is not None else "n/a"
        if row is None:
            cells = ["not measured"]
            used_adjusted = None
        else:
            used = row["card_used_mib"]
            cells = [f"{row['verdict']} ({used} MiB)" if used is not None else row["verdict"]]
            used_adjusted = _adjusted(used, base_baseline)
        for entry, rows in zip(others, other_rows):
            match = rows.get(key)
            if match is None:
                cells.append("not measured")
                continue
            match_adjusted = _adjusted(match["card_used_mib"], entry["baseline_mib"])
            state, _ = detect_fallback(used_adjusted, match_adjusted)
            cell = f"{match['verdict']}"
            if match["card_used_mib"] is not None:
                cell += f" ({match['card_used_mib']} MiB)"
            if state == "FALLBACK":
                cell += " ⚠️ **FALLBACK**"
            elif state == "UNKNOWN":
                # UNKNOWN used to render as a bare number, which is the exact
                # thing this whole file argues against: a reading that means
                # "these two passes cannot be compared" looked identical to one
                # that means "compression worked". Real case that exposed it -
                # nomic-embed-text measured 2216/2603/2708 MiB across f16, q8_0
                # and q4_0, i.e. MORE memory with a smaller cache, which is not
                # a thing compression does. Marked so it reads as unexplained
                # rather than as an all-clear.
                cell += " ⚠️ **UNKNOWN**"
            cells.append(cell)
        lines.append(f"| `{model}` | {ctx} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "`FALLBACK` means the quantized cache setting silently did nothing on",
        "this architecture — the memory did not move. It is not an error state",
        "you can see any other way.",
        "",
        "`UNKNOWN` means the quantized pass used **more** memory than `f16`,",
        "which is not something compression does. Treat it as a reading that",
        "could not be compared rather than as a result: it usually means the",
        "model is too small for its cache to matter and the number is dominated",
        "by allocator noise. Re-measure on an idle card before drawing anything",
        "from it.",
        "",
        "A row that reads `SPILLED` under `f16` is a special case: its `f16`",
        "figure was capped by the card, because the part that did not fit was",
        "in system RAM and never counted. The memory delta for such a row",
        "therefore **understates** the saving, sometimes badly. The verdict",
        "changing from `SPILLED` to `MEASURED` is the real result there; the",
        "MiB difference is not.",
        "",
        "## What this cannot tell you",
        "",
        "It measures whether a model **fits**. It says nothing about whether a",
        "compressed cache made the model **worse**. Memory is easy to measure and",
        "quality is not. Do not quote this file as evidence about output quality.",
        "",
    ]
    return "\n".join(lines)


def _pass(cache_type: str, baseline_mib: int, rows: list[dict],
          flash_attention: bool = True, taken: str = "2026-08-11") -> dict:
    return {"cache_type": cache_type, "baseline_mib": baseline_mib, "taken": taken,
            "flash_attention": flash_attention, "rows": rows}


def _row(model: str = "m/model:1b", num_ctx: int | None = 16384,
         verdict: str = "MEASURED", card_used_mib: int | None = 20000) -> dict:
    return {"model": model, "num_ctx": num_ctx, "verdict": verdict,
            "card_used_mib": card_used_mib}


def _marker_present(output: str) -> bool:
    # Matches the cell marker, not the word: the prose below the table also
    # says FALLBACK, so a bare substring test would be true of every report.
    return "⚠️ **FALLBACK**" in output


def _unknown_marker_present(output: str) -> bool:
    return "⚠️ **UNKNOWN**" in output


def _equal_column_counts(output: str) -> bool:
    header = next(line for line in output.splitlines() if line.startswith("| Model"))
    separator = next(line for line in output.splitlines() if line.startswith("|---"))
    return header.count("|") == separator.count("|")


# Each case is (description, passes, check). check receives the rendered
# markdown and returns True if the case passed. Without this table `render`
# has no test at all: FALLBACK_CASES only proves detect_fallback is correct in
# isolation, not that render actually calls it correctly or displays what it
# returns.
RENDER_CASES = (
    ("identical memory, same baseline, improved verdict must still warn",
     [_pass("f16", 2000, [_row(verdict="SPILLED", card_used_mib=22000)]),
      _pass("q8_0", 2000, [_row(verdict="MEASURED", card_used_mib=22000)])],
     _marker_present),
    ("a real saving with the same baseline must not warn",
     [_pass("f16", 2000, [_row(card_used_mib=22000)]),
      _pass("q8_0", 2000, [_row(card_used_mib=20000)])],
     lambda out: not _marker_present(out)),
    ("baseline drift masking no real change - the Finding 1 regression test",
     [_pass("f16", 2400, [_row(card_used_mib=23000)]),
      _pass("q8_0", 1920, [_row(card_used_mib=22520)])],
     _marker_present),
    ("f16-only pass keeps header and separator column counts equal",
     [_pass("f16", 2000, [_row()])],
     _equal_column_counts),
    # A quantized pass that used MORE memory than f16 is not a saving and not a
    # fallback - it is a reading that cannot be explained, and detect_fallback
    # returns UNKNOWN for it. render used to drop that state on the floor and
    # print a bare number, so "these two passes cannot be compared" looked
    # exactly like "compression worked". Found in the real 2026-08-12 survey:
    # nomic-embed-text read 2216/2603/2708 MiB across f16/q8_0/q4_0.
    ("a quantized pass using MORE memory must be marked, not shown bare",
     [_pass("f16", 2000, [_row(card_used_mib=20000)]),
      _pass("q8_0", 2000, [_row(card_used_mib=21500)])],
     _unknown_marker_present),
    ("an UNKNOWN cell must not be mislabelled as a FALLBACK",
     [_pass("f16", 2000, [_row(card_used_mib=20000)]),
      _pass("q8_0", 2000, [_row(card_used_mib=21500)])],
     lambda out: not _marker_present(out)),
)


def self_check() -> list[str]:
    problems: list[str] = []
    for description, f16, quant, expected in FALLBACK_CASES:
        got, _ = detect_fallback(f16, quant)
        if got != expected:
            problems.append(
                f"detect_fallback {description!r}: got {got}, expected {expected} "
                "— the detector is broken, so a setting that silently did "
                "nothing would be reported as a working saving")
    for description, passes, check in RENDER_CASES:
        output = render(passes)
        if not check(output):
            problems.append(
                f"render {description!r}: the rendered report did not satisfy "
                "its expectation — render's own logic, not just "
                "detect_fallback, can silently stop warning about a fallback")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("passes", nargs="*", help="pass JSON files from vram_survey.py")
    parser.add_argument("--out", help="write the markdown report here")
    parser.add_argument("--self-check", action="store_true",
                        help="prove the fallback detector still works, then exit")
    args = parser.parse_args()

    if args.self_check:
        problems = self_check()
        for problem in problems:
            print(problem, file=sys.stderr)
        print("self-check: OK" if not problems else "self-check: FAILED")
        return 1 if problems else 0

    if not args.passes or not args.out:
        parser.print_usage(sys.stderr)
        print("give at least one pass file and --out", file=sys.stderr)
        return 2

    passes = []
    for path in args.passes:
        with open(path, encoding="utf-8") as handle:
            passes.append(json.load(handle))
    if not any(p["cache_type"] == "f16" for p in passes):
        print("no f16 pass given. Without the baseline nothing can be compared "
              "and the fallback detection cannot run", file=sys.stderr)
        return 1

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(render(passes))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
